language: node_js
node_js:
  - '6'
cache: yarn
branches:
  only:
  - master
script:
  - 'yarn test'
  - 'yarn run lint'
notifications:
  email: false
deploy:
  provider: npm
  skip_cleanup: true
  email: 'chronobserver@disroot.org'
  on:
    tags: true
  api_key:
    secure: PPPJlBZlqAonFvE1dEy9iivdrmpriDjihX/YIM86dUXKfoHe27oTm5VHwdNW54wSnyAosDm5oAQJTAZ2dwtWF4BPnJ0nc5zmbyaTsFH8D7zS36e3gnbtd7qyA09aBnBCqdlKq0CJvnTSBlYlTySZke5Aglv6SVi2ZXhvEOCKw+0CT+SlWwMvkDVEtO4XxHLNsCe/1N0scS2vwCM04wnX23w5+GHJqIGHEDSB+LtmEzCrTYll6yQt0JHj1VBeS9ibHbr5jchsXS46RSFOnnzl5y7uNtQ/cOGzlQpV+1tIdQmTC/qV0Af8OZHkmd+J9f8Ja3k5BM6K54Yt2l7wmE9ybG1QhoWRf9WnOn+tyKK9sX9xQ3/d2w5AZ6L/+9+ov9U7EjFbgYbIiNWt9VK/l94t3MnKT7S0hRnSyFehsd0TGYOXIY7jv2i6swmfhWDPtYYkA0fJRhOhrad1ujQMdS1O6WmarLqmD4HArVCU2p/lPbBYTY6KUFo6cCJB4nZ0HrQcq4Aq7WbYNvWC4j0C7S+Uekq0NAZyfbJXjqIcUFeKDUettsnpJBVpQmFhyfPzZlkVUYhPxCr0VBVxfUGT1kfWfU8R2adMTdNPp1cmxcc+fHYj3MkkqM5+MjwV1yXitM3t5jQ552e+ebO29TkNs46cuoZ0YjDddttUr8CIbQr17pA=
