language: node_js
node_js: 8
cache: yarn
branches:
  only:
    - 'master'
    - '/^v\d(?:\.\d+){2}.*/'
script:
  - yarn lint
  - yarn test
notifications:
  email: false
deploy:
  provider: npm
  skip_cleanup: true
  email: chronobserver@disroot.org
  on:
    tags: true
  api_key:
    secure: xWRXGJs1n5XjPCkP+PnHJO37VfRuj2fMgh+W4zaxErEE51ecPLpgHgRJ/XpVZSaNhsoGmUik4a6pEcPpGiNiluVc8iB70ltMBOW5hdVkevkZRnW0tZSThCJm2tR2Wfx8s3MjXBSpYc8hXSNFm+BcuYArnD3kOiHuAGSW6NsH3sg+g7kJduXN+VVZkmHK/1fK3yufxrs8/x5G1uKg83064ZXe7pfeYEgLhSCMO8nf0+WNtds2rlP+D8Tn92y68HWhOaRCBP2+ks9TpDt1i3uK0AOmEaWcCG+n+TkEpJxqnhY7cY7qIHGAt3UCflRgZ524atQ6fo4aD8tDWxDvQ3N9J6kZD1GJYS2/RUHJcdMpVt7hWSmPZbxAF3S7sLuOP5MOrUYGMKxlNIcbSzh0KuRIpBfRe7QihrDVKrGalR/gi/B8ZtfvM3D2ylevB3n8nSgVGUv4bPNsJ7WUbCtGwid7n/lfStRPOlTM7cpKii1yBfK7NWkAvZP8S/zTZuwiKIhAExRdr8cSP7aSkcwb0kd9YI+wC0Ff7uhzidCrZUvkJhm1rLnIB+g6re143EsSJA9S2QU7mABhqC4bmf8YfQoBhBwIDSi+C+UFU5oZZsTdNyKhWQV8tGgxGa5GHjGgH4xnhzZX0eKL+uiqoTI//ftWKg786X3sqiMQpsXYWZo5PZo=
before_script:
- rm -f /home/travis/build/ObserverOfTime/transfer.js/npm-debug.log

