name: Build

on: [push, pull_request]

jobs:
  build:
    if: |
      contains(github.event.commits[0].message, '[skip ci]') == false &&
      contains(github.event.commits[0].message, '[ci skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@1.1.0
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Coverage
        run: yarn cover
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      - name: Publish
        run: yarn publish --access public
        if: startsWith(github.ref, 'refs/tags')
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_REGISTRY_URL: npm.pkg.github.com
